"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";

type N = { id:string; source:"chat"|"group"; title:string; preview:string; createdAt:string; href:string };
const KEY="banda-chat-notifications-v1";
export default function BandaNotificationWidget({mode="all"}:{mode?:"chat"|"group"|"all"}){
 const router=useRouter(); const [items,setItems]=useState<N[]>([]); const [open,setOpen]=useState(false); const [uid,setUid]=useState("");
 const visible=useMemo(()=>items.filter(x=>mode==="all"||x.source===mode),[items,mode]);
 useEffect(()=>{void(async()=>{const {data}=await supabase.auth.getSession();if(!data.session?.user)return;setUid(data.session.user.id);try{setItems(JSON.parse(localStorage.getItem(KEY)||"[]"));}catch{}})()},[]);
 useEffect(()=>{if(uid)localStorage.setItem(KEY,JSON.stringify(items));},[items,uid]);
 useEffect(()=>{if(!uid)return;const c=supabase.channel(`banda-notifications-${uid}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages"},async({new:m}:any)=>{if(!m?.id||m.sender_id===uid)return;const {data:mem}=await supabase.from("conversation_members").select("user_id").eq("conversation_id",m.conversation_id).eq("user_id",uid).maybeSingle();if(!mem)return;const {data:conv}=await supabase.from("conversations").select("id,type,name").eq("id",m.conversation_id).maybeSingle();if(!conv)return;const source=conv.type==="group"?"group":"chat";const {data:p}=await supabase.from("profiles").select("full_name,username").eq("id",m.sender_id).maybeSingle();const name=p?.full_name?.trim()||p?.username||"Pengguna baru";const n:N={id:m.id,source,title:source==="group"?(conv.name||"Grup Banda Chat"):name,preview:m.content?.trim()||"Mengirim pesan baru",createdAt:m.created_at,href:source==="group"?`/chat/grup?group=${m.conversation_id}`:`/chat?conversation=${m.conversation_id}`};setItems(v=>[n,...v.filter(x=>x.id!==n.id)].slice(0,100));}).subscribe();return()=>{void supabase.removeChannel(c)}},[uid]);
 const remove=(id:string)=>setItems(v=>v.filter(x=>x.id!==id)); const clear=()=>setItems(v=>mode==="all"?[]:v.filter(x=>x.source!==mode));
 return <div className="fixed bottom-4 right-4 z-[60]">{open&&<div className="mb-2 w-[min(92vw,360px)] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-3"><div><b className="text-sm">Notifikasi</b><div className="text-[11px] text-slate-500">Pesan pribadi dan grup</div></div>{visible.length>0&&<button onClick={clear} className="text-xs text-red-600">Hapus semua</button>}</div><div className="max-h-[55vh] overflow-y-auto">{!visible.length?<div className="p-6 text-center text-sm text-slate-500">Belum ada notifikasi baru.</div>:visible.map(n=><div key={n.id} className="flex gap-2 border-b p-3"><button onClick={()=>{remove(n.id);setOpen(false);router.push(n.href)}} className="min-w-0 flex-1 text-left"><div className="font-semibold text-sm truncate">{n.source==="group"?"👥":"💬"} {n.title}</div><div className="mt-1 text-xs text-slate-600">{n.preview}</div><div className="mt-1 text-[10px] text-slate-400">{new Date(n.createdAt).toLocaleString("id-ID")}</div></button><button onClick={()=>remove(n.id)} className="text-slate-400">✕</button></div>)}</div></div>}<button onClick={()=>setOpen(v=>!v)} aria-label="Notifikasi" className="relative h-12 w-12 rounded-full bg-blue-600 text-white shadow-lg flex items-center justify-center border-2 border-white">🔔{visible.length>0&&<span className="absolute -right-1 -top-1 flex h-5 min-w-5 items-center justify-center rounded-full bg-red-500 px-1 text-[10px] font-bold">{visible.length>99?"99+":visible.length}</span>}</button></div>;
}
